# Generated by Django 4.2.4 on 2023-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='table_num',
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='table_name',
            field=models.CharField(blank=True, choices=[('Two-Top', 'Two-Top'), ('Four-Top', 'Four-Top'), ('Six-Top', 'Six-Top'), ('Eight-Top', 'Eight-Top'), ('Large Party', 'Large Party Table (for ten people)')], max_length=30, null=True),
        ),
    ]
