# Generated by Django 4.2.4 on 2023-09-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tables',
            fields=[
                ('tab_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
