# Generated by Django 4.2.4 on 2023-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_tablebooking_table_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='table_num',
            field=models.CharField(blank=True, choices=[('Two-Top 1', 'Two-Top 1'), ('Two-Top 2', 'Two-Top 2'), ('Two-Top 3', 'Two-Top 3'), ('Four-Top 1', 'Four-Top 1'), ('Four-Top 2', 'Four-Top 2'), ('Four-Top 3', 'Four-Top 3'), ('Six-Top 1', 'Six-Top 1'), ('Six-Top 2', 'Six-Top 2'), ('Six-Top 3', 'Six-Top 3'), ('Eight-Top 1', 'Eight-Top 1'), ('Eight-Top 2', 'Eight-Top 2'), ('Eight-Top 3', 'Eight-Top 3'), ('Large Party 1', 'Large Party 1'), ('Large Party 2', 'Large Party 2'), ('Large Party 3', 'Large Party 3')], max_length=30, null=True),
        ),
    ]
