# Generated by Django 4.2.4 on 2023-09-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_reservation_id_reservation_tab_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='tab_id',
            new_name='reservation_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='table',
            new_name='table_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
