# Generated by Django 4.2.4 on 2023-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_phone_number_reservation_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
    ]
