# Generated by Django 4.2.4 on 2023-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_menus_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
