# Generated by Django 4.2.4 on 2023-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_menus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
