# Generated by Django 4.2.4 on 2023-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_menus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='category',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Chineese', 'Chineese'), ('North Indian', 'North Indian'), ('Soft drinks', 'Soft drinks')], default='', max_length=50),
        ),
    ]
