# Generated by Django 4.2.4 on 2023-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_menus_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='sub_submenu',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='menus',
            name='submenu',
            field=models.CharField(blank=True, choices=[('Breads', 'Breads'), ('Curries', 'Curries'), ('Rice Dishes', 'Rice Dishes'), ('Seafoods', 'Seafoods'), ('Deserts', 'Deserts'), ('Appetizers', 'Appetizers'), ('Main Course', 'Main Course'), ('Tandoori delights', 'Tandoori delights'), ('Chaats', 'Chaats'), ('Rolls & Grills', 'Rolls & Grills'), ('Hot Beverage', 'Hot Beverage'), ('Cold Beverage', 'Cold Beverage')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='menus',
            name='category',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Chineese', 'Chineese'), ('North Indian', 'North Indian'), ('Arabian', 'Arabian'), ('Deserts', 'Deserts'), ('Beverages', 'Beverages')], default='', max_length=50),
        ),
    ]
