# Generated by Django 4.2.4 on 2023-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_reservation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
