# Generated by Django 4.2.4 on 2023-09-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_reservation_menu_desc_reservation_menu_name_and_more'),
    ]

    