# Generated by Django 4.2.4 on 2023-09-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_reservation_menu_desc_and_more'),
    ]

    