# Generated by Django 4.2.4 on 2023-09-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_reservation_menu_desc_and_more'),
    ]

    
