# Generated by Django 4.2.4 on 2023-09-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_reservation_menu_price_alter_reservation_menu_name'),
    ]

    