# Generated by Django 4.2.4 on 2023-09-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_reservation_menu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='menu_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='menu_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tables'),
        ),
    ]
