# Generated by Django 4.2.4 on 2023-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_reservation_menu_name_reservation_menu_price_and_more'),
    ]

    