# Generated by Django 4.2.4 on 2023-09-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
