# Generated by Django 4.2.4 on 2023-09-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='category',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Chineese', 'Chineese'), ('North Indian', 'North Indian'), ('Arabian', 'Arabian'), ('Beverages', 'Beverages')], default='', max_length=50),
        ),
    ]
