# Generated by Django 4.2.4 on 2023-09-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_menus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='submenu',
            field=models.CharField(blank=True, choices=[('Breads', 'Breads'), ('Curries', 'Curries'), ('Rice Dishes', 'Rice Dishes'), ('Appetizers', 'Appetizers'), ('Main Course', 'Main Course'), ('Breads & Accompaniments', 'Breads & Accompaniments'), ('Rolls & Grills', 'Rolls & Grills'), ('Hot Beverage', 'Hot Beverage'), ('Cold Beverage', 'Cold Beverage')], default='', max_length=50),
        ),
    ]
