# Generated by Django 4.2.4 on 2023-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_customuser_role_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'CUSTOMER'), (2, 'EMPLOYEE')], default='1', null=True),
        ),
    ]
