# Generated by Django 4.2.4 on 2023-09-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_employee_address_employee_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_proof_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
