# Generated by Django 4.2.4 on 2023-09-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_number',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
