# Generated by Django 4.2.4 on 2023-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_employee_address_alter_employee_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
