# Generated by Django 4.2.4 on 2023-09-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
