# Generated by Django 4.2.4 on 2023-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_billinginformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
