# Generated by Django 4.2.4 on 2023-09-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_billinginformation_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='not_paid', max_length=20),
        ),
    ]
