# Generated by Django 4.2.4 on 2023-10-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('approved', 'Approved'), ('declined', 'Declined')], default=None, max_length=10, null=True),
        ),
    ]
